version: 2.1

jobs:
  focal_gcc9_coverage:
    docker:
    - image: circleci/buildpack-deps:focal
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_focal_gcc9_coverage.sh
  focal_gcc9_asan:
    docker:
    - image: circleci/buildpack-deps:focal
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_focal_gcc9_asan.sh
  focal_gcc9_docs:
    docker:
    - image: circleci/buildpack-deps:focal
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_focal_gcc9_docs.sh
  focal_clang9:
    docker:
    - image: circleci/buildpack-deps:focal
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_focal_clang9.sh
  bionic_clang6_release:
    docker:
    - image: circleci/buildpack-deps:bionic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_bionic_clang6_release.sh

workflows:
  version: 2.1
  all_builds:
    jobs:
    - focal_gcc9_coverage
    - focal_gcc9_asan
    - focal_clang9
    - bionic_clang6_release
    - focal_gcc9_docs
